todolist_project/todo/urls.py
from django.urls import path
from todo.views import TodoDAO
urlpatterns = [
    path('', TodoDAO.index, name='todo-index'),

    #auth
    path('signup/', TodoDAO.sign_up, name='todo-signup'),
    path('login/', TodoDAO.log_in, name='todo-login'),
    path('logout/', TodoDAO.log_out, name='todo-logout'),
    path('create_todo/', TodoDAO.Create_Todo, name='todo-create')
]

todolist_project/todolist_project/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),
]

todolist_project/todo/models.py
from django.db import models
from django.contrib.auth.models import User
class TodoModel(models.Model):
    title = models.CharField(max_length=100)
    memo = models.CharField(blank=True, max_length=1000)
    create_at = models.DateTimeField(auto_now_add=True)
    complite_at = models.DateTimeField(null=True,blank=True)
    important = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return self.title

todolist_project/todo/forms.py
from django.forms import ModelForm

from todo.models import TodoModel


class TodoForm(ModelForm):
    class Meta:
        model = TodoModel
        fields = ['title', 'memo', 'important']



todolist_project/todo/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest
from django.template.response import TemplateResponse
from django.views import View
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from  django.db import IntegrityError
from django.contrib.auth import login, authenticate, logout
from django.utils.functional import SimpleLazyObject
from todo.forms import TodoForm
from todo.models import TodoModel

class TodoDAO(View):
    def sign_up(request:HttpRequest)->TemplateResponse:
        if request.method == 'GET':
            return render(request, 'todo/sign_up.html',context={'form': UserCreationForm})
        if request.method == 'POST':
            try:
                if request.POST['password1'] == request.POST['password2']:
                    user = User.objects.create_user(username=request.POST['username'],password=request.POST['password1'])
                    user.save()
                    login(request,user)
                    return redirect('todo-index')

                else:
                    
                    return render(request, 'todo/sign_up.html',context={'form': UserCreationForm, 'error':'Password is not'})
            except IntegrityError:
                return render(request, 'todo/sign_up.html',
                              context={'form': UserCreationForm, 'error': 'Its user already exsists'})

    def log_in(request:HttpRequest)->TemplateResponse:
        if request.method == 'GET':
            return render(request, 'todo/log_in.html', context={'form':AuthenticationForm})
        if request.method == 'POST':
            user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
            if user is None:
                return render(request, 'todo/log_in.html', context={'form':AuthenticationForm,'error':"This username or password doesnt exists"})
            else:
                login(request,user)
                return redirect('todo-index')

    def log_out(request:HttpRequest)->TemplateResponse:
        if request.method == 'POST':
            logout(request)
            return render(request, 'todo/index.html')
    def index(request:HttpRequest)->TemplateResponse:
        if request.user.pk == None:
            return render(request, 'todo/index.html')

        else:
            todos = TodoModel.objects.filter(user=request.user, complite_at__isnull=True)
            return render(request, 'todo/index.html', context={'todos':todos})

    def Create_Todo(request:HttpRequest)->TemplateResponse:
        if request.method == 'GET':
            return render(request, 'todo/create_Todo.html', context={'form':TodoForm})
        if request.method == 'POST':
            form = TodoForm(request.POST)
            newTodo = form.save(commit=False)
            newTodo.user = request.user
            newTodo.save()
            return redirect('todo-index')



todolist_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <form action="{%url 'todo-logout'%}" method="POST">
                    {% if user.is_authenticated%}
                    {% csrf_token %}
                    <li class="nav-item">
                        <a aria-current="page" class="nav-link active" href="#">
                            <button type="submit", id="log-out">Log out</button>
                        </a>
                    </li>
                    {% else %}

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'todo-signup'%}">Sign up</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'todo-login' %}">Log in</a>
                    </li>

                    {%endif%}

                </form>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'todo-create' %}">Create todo</a>
                    </li>
            </ul>
        </div>
    </div>
</nav>
{%block content%}{%endblock%}
</body>
<style>
    #id_username_helptext,#id_password1_helptext{
    display:none
    }
    #id_password1_helptext{
    display:none
    }
    #id_password2_helptext{
    display:none
    }
    button{
    border-radius:20px
    }

    label[for="id_username"]{
    position:absolute;
    top:140px;
    left:300px
    }
    #id_username{
    position:absolute;
    top:140px;
    left:400px;
    }

    label[for='id_password1']{
    position:absolute;
    top:180px;
    left:300px;
    }
    #id_password1{
    position:absolute;
    top:180px;
    left:400px;
    }

    label[for='id_password2']{
    position:absolute;
    top:220px;
    left:300px;
    }
    #id_password2{
    position:absolute;
    top:220px;
    left:470px;
    }

    button{
    position:absolute;
    left:400px;
    top:260px
    }
    label[for='id_password']{
    position:absolute;
    top:180px;
    left:300px;
    }
    #id_password{
    position:absolute;
    top:180px;
    left:400px;
    }

    label[for="id_title"]{
    position:absolute;
    top:140px;
    left:300px;
    }
    #id_title{
    position:absolute;
    top:140px;
    left:350px;
    }

    label[for="id_memo"]{
    position:absolute;
    top:180px;
    left:300px;
    }
    #id_memo{
    position:absolute;
    top:180px;
    left:350px;
    }

    label[for="id_important"]{
    position:absolute;
    top:220px;
    left:300px;
    }
    #id_important{
    position:absolute;
    top:228px;
    left:380px;
    }

    #log-out{
    position:relative;
    left:0px;
    top:0px;
    }

    .memos{
    display:inline-flex;
    margin:10px;
    padding:10px;
    width:200px;

    }
</style>
</html>



todolist_project/todo/templates/todo/create_Todo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Todo</title>
</head>
<body>
{% extends 'base.html' %}
    {%block content%}
    {{error}}
    <form method="POST">
         {% csrf_token %}{{form}}
        <button type="submit">Save</button>
    </form>
    {%endblock%}
</body>
</html>

todolist_project/todo/templates/todo/index.html
{%extends 'base.html'%}
{%block content%}
<br>

{% if user.is_authenticated%}
{%for todo in todos%}
<div class="memos">
<h3>{{todo.title}} <br><br> {{todo.memo}}</h3>
</div>
{%endfor%}
{%endif%}
{%endblock%}

todolist_project/todo/templates/todo/log_in.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Log in</title>
</head>
<body>
{% extends 'base.html' %}
    {%block content%}
    {{error}}
    <form method="POST">
         {% csrf_token %}{{form}}
        <button type="submit">Log in</button>
    </form>
    {%endblock%}
</body>
</html>

todolist_project/todo/templates/todo/sign_up.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign up</title>
</head>
<body>
    {% extends 'base.html' %}
    {%block content%}
    {{error}}
    <form method="POST">
         {% csrf_token %}{{form}}
        <button type="submit">Sign up</button>
    </form>
    {%endblock%}
</body>
</html>